# Auto-generated by Stats-AI — do not edit manually
# Slots filled by Claude: dep_var, indep_vars, data_path, transformations
#   (data is mounted at /data/data.csv inside the container)
#   {{DEP_VAR}}         - dependent variable column name
#   {{INDEP_VARS}}      - independent variables joined with " + " (R formula syntax)
#   {{TRANSFORMATIONS}} - optional R code block for variable transformations

suppressPackageStartupMessages(library(lmtest))
suppressPackageStartupMessages(library(sandwich))
suppressPackageStartupMessages(library(car))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(jsonlite))

# ── Data loading ──────────────────────────────────────────────────────────────
df <- read.csv("/data/data.csv", stringsAsFactors = FALSE)
df$date <- as.Date(df$date)

# ── Transformations (Claude fills this block) ─────────────────────────────────
{{TRANSFORMATIONS}}

# ── Model ─────────────────────────────────────────────────────────────────────
formula_str <- "{{DEP_VAR}} ~ {{INDEP_VARS}}"
model <- lm(as.formula(formula_str), data = df)
coef_summary <- summary(model)$coefficients
ci <- confint(model)

# ── Diagnostics ───────────────────────────────────────────────────────────────
bp_test  <- bptest(model)
dw_test  <- dwtest(model)
vif_vals <- tryCatch(vif(model), error = function(e) NULL)

# Shapiro-Wilk: requires 3 <= n <= 5000; sample if too large, skip if too small
resids  <- residuals(model)
n_resid <- length(resids)
if (n_resid < 3) {
  sw_test <- NULL
} else if (n_resid > 5000) {
  sw_test <- shapiro.test(sample(resids, 5000))
} else {
  sw_test <- shapiro.test(resids)
}

# ── Coefficient plot ──────────────────────────────────────────────────────────
coef_df <- data.frame(
  variable = rownames(ci)[-1],
  estimate = coef(model)[-1],
  ci_lower = ci[-1, 1],
  ci_upper = ci[-1, 2]
)
p_coef <- ggplot(coef_df, aes(x = variable, y = estimate)) +
  geom_point(color = "#6366f1") +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2, color = "#6366f1") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#94a3b8") +
  coord_flip() +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background  = element_rect(fill = "transparent", color = NA),
    panel.grid.major = element_line(color = "#334155"),
    text             = element_text(color = "#f1f5f9")
  ) +
  labs(title = "Coefficient Estimates", x = NULL, y = "Estimate")

# ── Residual plot ─────────────────────────────────────────────────────────────
resid_df <- data.frame(fitted = fitted(model), residuals = residuals(model))
p_resid <- ggplot(resid_df, aes(x = fitted, y = residuals)) +
  geom_point(alpha = 0.6, color = "#6366f1") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "#94a3b8") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background  = element_rect(fill = "transparent", color = NA),
    panel.grid.major = element_line(color = "#334155"),
    text             = element_text(color = "#f1f5f9")
  ) +
  labs(title = "Residuals vs Fitted", x = "Fitted Values", y = "Residuals")

# ── Assemble output ───────────────────────────────────────────────────────────
coef_rows <- lapply(rownames(coef_summary), function(nm) {
  list(
    variable  = nm,
    estimate  = round(coef_summary[nm, "Estimate"], 6),
    std_error = round(coef_summary[nm, "Std. Error"], 6),
    t_stat    = round(coef_summary[nm, "t value"], 4),
    p_value   = round(coef_summary[nm, "Pr(>|t|)"], 6),
    ci_lower  = round(ci[nm, 1], 6),
    ci_upper  = round(ci[nm, 2], 6)
  )
})

vif_out <- if (!is.null(vif_vals)) as.list(round(vif_vals, 4)) else list()

# Handle DW p-value: can be NA for some time series configurations
dw_p <- if (is.na(dw_test$p.value)) NULL else round(dw_test$p.value[[1]], 6)

# Shapiro-Wilk result: NULL if n < 3
sw_result <- if (!is.null(sw_test)) {
  list(
    statistic = round(sw_test$statistic[[1]], 4),
    p_value   = round(sw_test$p.value[[1]], 6)
  )
} else {
  list(statistic = NA_real_, p_value = NULL)
}

output <- list(
  coefficients = coef_rows,
  model_summary = list(
    r_squared          = round(summary(model)$r.squared, 6),
    adj_r_squared      = round(summary(model)$adj.r.squared, 6),
    f_statistic        = round(summary(model)$fstatistic[1], 4),
    f_p_value          = round(pf(summary(model)$fstatistic[1],
                                  summary(model)$fstatistic[2],
                                  summary(model)$fstatistic[3],
                                  lower.tail = FALSE), 6),
    n_obs              = nrow(df),
    degrees_of_freedom = model$df.residual
  ),
  diagnostics = list(
    breusch_pagan = list(
      statistic = round(bp_test$statistic[[1]], 4),
      p_value   = round(bp_test$p.value[[1]], 6),
      df        = as.integer(bp_test$parameter[[1]])
    ),
    durbin_watson = list(
      statistic = round(dw_test$statistic[[1]], 4),
      p_value   = dw_p
    ),
    vif = vif_out,
    shapiro_wilk = sw_result
  ),
  plotly_charts = list(
    list(name = "coefficient_plot", json = plotly_json(ggplotly(p_coef), pretty = FALSE)),
    list(name = "residual_plot",    json = plotly_json(ggplotly(p_resid), pretty = FALSE))
  )
)

cat(toJSON(output, auto_unbox = TRUE))
